server:
  port: 9090
spring:
  cloud: 
   gateway: 
    routes:
      - id: UserManagement
        uri: 'http://localhost:8081'
        predicates:
          - Path=/usermgmt/**
      - id: JobManagement
        uri: 'http://localhost:8082'
        predicates:
          - Path=/jobmgmt/**